name: Boilerplate => Eslint, Prettier and Jest tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - template/**/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint_type_test:
    name: Run eslint, prettier, type check and jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/deps-setup
        with:
          working_directory: ./template
      - name: Run Eslint
        run: yarn lint:rules
        working-directory: ./template
      - name: Run Prettier
        run: yarn lint:code-format
        working-directory: ./template
      - name: Run Typescript check
        run: yarn lint:type-check
        working-directory: ./template
      - name: Run Jest tests
        run: yarn test
        working-directory: ./template
