name: CD workflow to NPM publish

on:
  release:
    types: [published]

jobs:
  publish:
    if: "!github.event.release.prerelease"
    uses: ./.github/actions/deploy-npm
  rc_publish:
    if: "!github.event.release.prerelease"
    uses: ./.github/actions/deploy-npm
    with: ${{ github.event.release.tag_name }}
