#name: CD - Next
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  release:
#    uses: ./.github/workflows/w-deploy.yml
#    with:
#      tag: "next" #TODO: how to add incremental
#  bump_version:
#    uses: ./.github/workflows/w-bump-version.yml
#    with:
#      tag: "next"
