on:
  workflow_call:
    inputs:
      working_directory:
        description: 'The directory where the install command will be run'
        required: true
        type: string

jobs:
  setup:
    name: Install dependencies with cache
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.working_directory }}/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ${{ inputs.working_directory }}
